esphome:
  name: intelliflo
  friendly_name: Intelliflo

esp32:
  board: m5stack-core-esp32

logger:
  level: VERBOSE
  baud_rate: 

api:
  encryption:
    key: "your_key"

ota:
  - platform: esphome
    password: !secret intelliflo_ota_password

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

external_components:
  - source: github://XMaarten/ESPHome-Pentair-Intelliflo@main
    components: [pentair_intelliflo]
    refresh: 0s

uart:
  - id: uart_modbus_client
    tx_pin: 19
    rx_pin: 22
    baud_rate: 9600

pentair_intelliflo:

sensor:
  - platform: pentair_intelliflo
    power:
      name: "Power"
    rpm:
      name: "RPM"

binary_sensor:
  - platform: pentair_intelliflo
    running:
      name: "Running"

text_sensor:
  - platform: pentair_intelliflo
    program:
      name: "Program"

number: # Not implemented yet
  - platform: pentair_intelliflo
    name: "Pool Pump RPM"
    id: id_number_rpm
    step: 100
    min_value: 1000
    max_value: 2600

switch: # Not implemented yet
  - platform: pentair_intelliflo
    name: Pool Pump Switch
    id: id_switch

button:
  - platform: template
    name: Set Pump ECO
    on_press:
      then:
        - number.set:
            id: id_number_rpm
            value: 1200
  - platform: template
    name: Set Pump NORMAL
    on_press:
      then:
        - number.set:
            id: id_number_rpm
            value: 1500
  - platform: template
    name: Set Pump HI
    on_press:
      then:
        - number.set:
            id: id_number_rpm
            value: 2500
