esphome:
  name: intelliflo
  friendly_name: Intelliflo

esp32:
  board: m5stack-core-esp32

logger:
  level: VERBOSE
  baud_rate: 

api:
  encryption:
    key: "your_key"

ota:
  - platform: esphome
    password: !secret intelliflo_ota_password

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

external_components:
  - source: github://XMaarten/ESPHome-Pentair-Intelliflo@main
    components: [pentair_intelliflo]
    refresh: 0s

uart:
  - id: uart_modbus_client
    tx_pin: 19
    rx_pin: 22
    baud_rate: 9600

pentair_intelliflo:
  id: pentairpump

sensor:
  - platform: pentair_intelliflo
    power:
      name: "Power"
    rpm:
      name: "RPM"

binary_sensor:
  - platform: pentair_intelliflo
    running:
      name: "Running"

select:
  - platform: template
    name: PumpProgram
    id: pumpprogram
    options:
     - "Program 1"
     - "Program 2"
     - "Program 3"    
     - "Program 4"    
    initial_option: "Program 1"
    optimistic: true    
    on_value:
      then:
      - lambda: |-
         auto program = i + 1;
         id(pentairpump).commandLocalProgram(program);
